server:
  port: 9007
spring:
  application:
    name: tensquare-search
  output:
    ansi:
      enabled: always
  data:
    elasticsearch:
      cluster-nodes: 192.168.132.129:9300
logging:
  config: classpath:logback-spring.xml