server:
  port: 9007
spring:
  application:
    name: tensquare-search
  output:
    ansi:
      enabled: always
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
logging:
  config: classpath:logback-spring.xml