server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  output:
    ansi:
      enabled: always
  redis:
    host: 192.168.132.129
  rabbitmq:
    host: 192.168.132.129
logging:
  config: classpath:logback-spring.xml