server:
  port: 9006
spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: 192.168.132.129
      database: spitdb
  redis:
    host: 192.168.132.129
logging:
  config: classpath:logback-spring.xml





